persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# Standard MQTT (for ESP32 & Python Client)
listener 1883
protocol mqtt
allow_anonymous true

# Websockets (for your Browser Wrapper)
listener 9001
protocol websockets
allow_anonymous true